version: '3'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    container_name: postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/datavolumes
      - ./sql/init.sql:/docker-entrypoint-initdb.d/main.sql
    ports:
      - "15432:5432"
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WEATHER_API_KEY=d33f5b33f0004357804211001222501
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2.2.2
    environment:
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
      - WEATHER_API_KEY=d33f5b33f0004357804211001222501
    volumes:
      - airflow_scheduler_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2.2.2
    environment:
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
      - WEATHER_API_KEY=d33f5b33f0004357804211001222501
    volumes:
      - airflow_worker_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
  airflow:
    image: docker.io/bitnami/airflow:2.2.2
    environment:
      #      - AIRFLOW_USERNAME=user
      #      - AIRFLOW_PASSWORD=bitnami
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default
      - WEATHER_API_KEY=d33f5b33f0004357804211001222501
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
